sudo: required
dist: trusty
before_install:
install:
before_script:
script:
  - echo ${RELEASE_CODENAME} > releases
  - ./package.sh
after_failure:
after_success:
env:
  matrix:
    - RELEASE_CODENAME=trusty
    - RELEASE_CODENAME=xenial
