sudo: required
dist: trusty
before_install:
  - $(grep -F apt package.sh)
install:
before_script:
  - for r in $(cat releases); do pbuilder-dist ${r} create; done
script:
  ./package.sh
after_failure:
after_success:
